name: Build test

on: ["push"]

jobs:
  pytest_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Start Container
        run: |
          docker-compose build
          docker-compose up -d

      - name: Build sveltekit
        run: |
          docker container exec svelte_container npm run build